web/router.ex
defmodule MusicQuiz.Router do
  use MusicQuiz.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.EnsureAuthenticated, handler: MusicQuiz.Token
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MusicQuiz do
    pipe_through :browser # Use the default browser stack

    get "/", QuizController, :index
    resources "/genres", GenreController, only: [:index, :show]
    resources "/artists", ArtistController, only: [:index, :show]
    resources "/quizzes", QuizController, only: [:show, :index]
    resources "/registrations", RegistrationController, only: [:new, :create]
    resources "/sessions", SessionController, only: [:new, :create]
    delete "/sessions", SessionController, :delete
  end

  scope "/", MusicQuiz do
    pipe_through [:browser, :browser_auth]
    resources "/users", UserController, only: [:show, :update]
  end

  scope "/api", MusicQuiz do
    pipe_through :api
    get "/quizzes/:id", Api.QuizController, :show
    post "/users/:user_id/completed_quizzes", Api.CompletedQuizController, :create
  end
end

web/views/layout_view.ex
defmodule MusicQuiz.LayoutView do
  use MusicQuiz.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Music Trivia</title>
    <script src="https://use.fontawesome.com/3787ac236a.js"></script>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <!--- Nav Bar --->
  <div class="container nav_container">
    <header class="nav column">
      <ul>
        <li>
          <h3><%= link("MusicQuizz", to: "/") %></h3>
        </li>
        <%= if logged_in?(@conn) do %>
          <li>
            <h6><%= link("Log Out", to: session_path(@conn, :delete), method: :delete) %></h6>
          </li>
          <li>
            <h6><%= link("Your Profile", to: "/users/#{current_user(@conn).id}") %></h6>
          </li>
        <% else %>
          <li>
            <h6><%= link("Sign Up", to: registration_path(@conn, :new)) %></h6>
          </li>
          <li>
            <h6><%= link("Log In", to: session_path(@conn, :new)) %></h6>
          </li>
        <% end %>
      </ul>
      <hr/>
    </header>
  </div>

  <body>
    <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
    <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

    <main role="main">
      <%= render @view_module, @view_template, assigns %>
    </main>

  <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>